# t-sne

model_type: 'bendr'

ckpt_path: '/path/to/your/code'
output_dir: '/path/to/your/code'

seed: 42

tag: ['bendr', 'tsne', 'test', '9']

datasets:
    tuab: 'finetune'
    workload: 'finetune'
    tusl: 'finetune'
    bcic_2a: 'finetune'
    adftd: 'finetune'
    things_eeg_2: 'finetune'
    mimul_11: 'finetune'
    tuev: 'finetune'
    seed: 'finetune'
    hmc: 'finetune'
    siena_scalp: 'finetune'
    motor_mv_img: 'finetune'
    seed_v: 'finetune_sub_dependent'

split: 'test'

num_batch: 1000
perplexity: 30
small_perplexity: 10
use_pca: false
pca_dims: 50
max_iter: 1000 